# -*- coding: utf-8 -*-
"""Forest Fire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p12XVHdQSzrsWebh8nLQFuq-HPUdiNRy
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

print("=" * 50)
print("AI BASED FOREST FIRE DETECTION SYSTEM")
print("=" * 50)

data = {
    "Temperature": [22,25,28,30,32,35,38,40,42,45,
                    24,26,29,31,34,37,39,41,43,46],

    "Humidity": [80,75,70,65,60,55,50,45,40,35,
                 78,73,68,63,58,53,48,43,38,33],

    "WindSpeed": [5,7,8,10,12,15,18,20,22,25,
                  6,8,9,11,13,16,19,21,23,26],

    "Rainfall": [10,8,6,5,4,3,2,1,0,0,
                 9,7,6,5,4,3,2,1,0,0],

    "Fire": [0,0,0,0,0,1,1,1,1,1,
             0,0,0,0,1,1,1,1,1,1]
}

df = pd.DataFrame(data)

print("\nDataset Loaded Successfully")
print(df.head())

X = df[["Temperature","Humidity","WindSpeed","Rainfall"]]
y = df["Fire"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("\nModel Training Completed Successfully")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:")
print(round(accuracy * 100, 2), "%")

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\n" + "=" * 50)
print("FOREST FIRE PREDICTION")
print("=" * 50)

temperature = float(input("Enter Temperature (°C): "))
humidity = float(input("Enter Humidity (%): "))
windspeed = float(input("Enter Wind Speed (km/h): "))
rainfall = float(input("Enter Rainfall (mm): "))

new_data = [[temperature, humidity, windspeed, rainfall]]

prediction = model.predict(new_data)

probability = model.predict_proba(new_data)

print("\nPrediction Result")
print("-" * 30)

if prediction[0] == 1:
    print("ALERT : HIGH RISK OF FOREST FIRE")
else:
    print(" SAFE : LOW RISK OF FOREST FIRE")

print("\nProbability Details")
print("No Fire Probability : {:.2f}%".format(probability[0][0]*100))
print("Fire Probability    : {:.2f}%".format(probability[0][1]*100))

print("\nSystem Completed Successfully")